### ISSUE TITLE
haxe ctags improvements

### ISSUE THREAD

**Issue by eliasku** [jdonaldson/vaxe#67]
Hi! First of all - Vaxe is impressive! I've started to learn vim for only one reason - vaxe is pretty stable, project/build system support is awesome (flow is here already!).

There is any plans on ctags improvements?
1. For example, adding `override` to function ctag?
2. Adding private keyword to `typedef`/`class`/`interface` declaration?
3. Adding `abstract` declaration?
4. Default `var _privateField` doesn't work now, do you suggest use implicit `private var _privateField`?
5. When `call vaxe#Ctags()`? Do you suggest to use keymapping, or default is already here? Or maybe it's automatically called when build targets changed?
6. Is it the latest ctags provided by you for Haxe 3 ?

**Comment by jdonaldson** [comment]
thanks for the kind words!

I just pushed a fix to vaxe for ctags.  The command :VaxeCtags should work properly now.  My own config was calling the method directly, so I never noticed.  If you sync, it should work fine.

Ctags could definitely use some improvement.  It's a bit frustrating because you can't really capture all of the syntax of haxe with simple regexes.  I've been spending more time trying to find a replacement.

I started with an older ctags version (referenced in the readme acknowledgements), and have been polishing it as I go.  They should be haxe 3 compatible.

**Comment by jdonaldson** [comment]
I just updated the ctags definition in the readme, and added support for abstracts.  I think that covers what you were asking.  Thanks for clearly enumerating them!  You can re-open this if I miss something.
