### ISSUE TITLE
Question: prevent :make from jumping to code on warnings

### ISSUE THREAD

**Issue by andypellucid** [jdonaldson/vaxe#74]
Hi, thanks for all your work on this plugin, it is awesome.

This might be more of a vim question, but is there any way to prevent the quick fix window from jumping to the source code location when a build error or warning occurs when compiling haxe code with `:make`?  I started looking through the code and vim docs, but I thought you might not mind giving me a hint if you knew.

**Comment by jdonaldson** [comment]
Thanks for the kind words!

You'll need to use ```:make!``` (with an exclamation point) in order to prevent jumping to an error.  You can see folks talking about the situation here:
http://stackoverflow.com/questions/2435876/vim-make-automatically-jumps-to-first-file-with-error

For what it's worth, I use an asynchronous make command called vim-dispatch courtesy of Tim Pope:
https://github.com/tpope/vim-dispatch

vim-dispatch is fast and interacts seamlessly with tmux (which I also recommend) : 
http://tmux.github.io/

I have ```:Make``` mapped to a leader command.  All of this does what I want:

1) It doesn't auto-jump to errors
2) It doesn't lock the editor on lengthy builds
3) It's near-effortless to launch from any make-able code.

**Comment by andypellucid** [comment]
Awesome, thanks.  Yeah, I noticed the :Make command by mistake - I think I'll switch to that!

Thanks again for creating this plugin!  (you can close this out)
