### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by OvermindDL1** [jdonaldson/vaxe#94]
This plugin tries to use Python2, which is no longer default in modern Ubuntu-based systems as vim is now built with Python3 and not Python 2, thus need to change `pyfile` to be `py3file` and change the HTMLParser import to the correct one.

**Comment by jdonaldson** [comment]
I'm not super motivated to solve this.  Vim for some reason did not allow for a python2 and python3 interpreter at the same time.  Most plugins are in python2, including my favorite one: https://github.com/Valloric/YouCompleteMe/issues/1140

I get what you're trying to say with "modern", but the reality is that most people are not running ubuntu 16.  At least not for a few years.

My suggestion is just to compile a new version of vim with python2 support.  My guess is that many people will have to deal with this for a while, since most vim python plugins are python2.

My long term plan here is actually to switch the plugin infrastructure over to lua.  I've even written a lua target for haxe, and hope to use it for this purpose:  http://haxe.org/blog/hello-lua

I'll leave this issue open for further discussion.

**Comment by OvermindDL1** [comment]
Hmm, I compiled YouCompleteMe without issue for this vim?  And it is not terribly 'modern', its been out for years, just not default in a lot of distributions until now.  But solving it just requires testing the python version (1 line) and conditionally calling the right command (adding another line, then an ending line for the blocks), fairly simple.  :-)

**Comment by jdonaldson** [comment]
I added python3 support, try it out and reopen if you see any issues!
